# Backend Docker Compose - Independiente
services:
  postgres:
    image: postgres:15
    container_name: backend-postgres-db
    restart: always
    environment:
      POSTGRES_DB: backend_sw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Puerto externo diferente para evitar conflictos
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-nestjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=backend_sw
      - DB_SSL=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-secreto_por_defecto}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-1d}
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
    networks:
      - backend-network

volumes:
  backend_postgres_data:

networks:
  backend-network:
    driver: bridge
    name: backend-network 